@hostname = localhost
@port = 3003
@host = {{hostname}}:{{port}}
@contentType = application/json

###

post http://{{host}}/api/login
Content-Type: {{contentType}}

{
  "username": "hellas",
  "password": "ahellas"
}

###

# post http://{{host}}/api/login
# Content-Type: {{contentType}}

# {
#   "username": "mluukkai",
#   "password": "sekret"
# }

###

# post http://{{host}}/api/login
# Content-Type: {{contentType}}

# {
#   "username": "vruuska",
#   "password": "password"
# }
