@hostname = localhost
@port = 3003
@host = {{hostname}}:{{port}}
@contentType = application/json
@baseUrl = http://{{host}}/api

###

# get all blogs 
GET {{baseUrl}}/blogs

###

# @prompt blogId
POST {{baseUrl}}/blogs/{{blogId}}/comments
Content-Type: application/json

{
  "text": "awesome article"
}

###

# @prompt blogId
POST {{baseUrl}}/blogs/{{blogId}}/comments
Content-Type: application/json

{
  "text": "a must read for every developer"
}
